package net.alarmtilt.cle.alarmis.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Sat Jan 13 18:20:17 CET 2018
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "com.alarmtilt.webservice.soap.res.v3", name = "AlarmTILTRestrictedWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface AlarmTILTRestrictedWebService {

    @WebMethod
    @RequestWrapper(localName = "listCmcInstance", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListCmcInstance")
    @ResponseWrapper(localName = "listCmcInstanceResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListCmcInstanceResponse")
    @WebResult(name = "listCmcInstanceResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.ListCmcInstanceResult listCmcInstance(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "listCmcInstanceParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.ListCmcInstanceParam listCmcInstanceParam
    );

    @WebMethod
    @RequestWrapper(localName = "importAgenda", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ImportAgenda")
    @ResponseWrapper(localName = "importAgendaResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ImportAgendaResponse")
    @WebResult(name = "importAgendaResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.ImportAgendaResult importAgenda(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "importAgendaParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.ImportAgendaParam importAgendaParam
    );

    @WebMethod
    @RequestWrapper(localName = "listContactAttribute", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListContactAttribute")
    @ResponseWrapper(localName = "listContactAttributeResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListContactAttributeResponse")
    @WebResult(name = "listContactAttributeResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.ListContactAttributeResult listContactAttribute(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "listContactAttributeParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.ListContactAttributeParam listContactAttributeParam
    );

    @WebMethod
    @RequestWrapper(localName = "validateSubscription", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ValidateSubscription")
    @ResponseWrapper(localName = "validateSubscriptionResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ValidateSubscriptionResponse")
    @WebResult(name = "validateSubscriptionResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.ValidateSubscriptionResult validateSubscription(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "validationSubscriptionParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.ValidateSubscriptionParam validationSubscriptionParam
    );

    @WebMethod
    @RequestWrapper(localName = "getContactUser", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.GetContactUser")
    @ResponseWrapper(localName = "getContactUserResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.GetContactUserResponse")
    @WebResult(name = "getContactUserResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.GetContactUserResult getContactUser(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "getContactUserParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.GetContactUserParam getContactUserParam
    );

    @WebMethod
    @RequestWrapper(localName = "listContact", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListContact")
    @ResponseWrapper(localName = "listContactResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListContactResponse")
    @WebResult(name = "listContactResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.ListContactResult listContact(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "listContactParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.ListContactParam listContactParam
    );

    @WebMethod
    @RequestWrapper(localName = "listSubscription", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListSubscription")
    @ResponseWrapper(localName = "listSubscriptionResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListSubscriptionResponse")
    @WebResult(name = "listSubscriptionResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.ListSubscriptionResult listSubscription(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "listSubscriptionParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.ListSubscriptionParam listSubscriptionParam
    );

    @WebMethod
    @RequestWrapper(localName = "listContactUser", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListContactUser")
    @ResponseWrapper(localName = "listContactUserResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListContactUserResponse")
    @WebResult(name = "listContactUserResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.ListContactUserResult listContactUser(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "listContactUserParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.ListContactUserParam listContactUserParam
    );

    @WebMethod
    @RequestWrapper(localName = "exportAgenda", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ExportAgenda")
    @ResponseWrapper(localName = "exportAgendaResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ExportAgendaResponse")
    @WebResult(name = "exportAgendaResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.ExportAgendaResult exportAgenda(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "exportAgendaParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.ExportAgendaParam exportAgendaParam
    );

    @WebMethod
    @RequestWrapper(localName = "sendNotification", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.SendNotification")
    @ResponseWrapper(localName = "sendNotificationResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.SendNotificationResponse")
    @WebResult(name = "sendNotificationResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.SendNotificationResult sendNotification(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "sendNotificationParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.SendNotificationParam sendNotificationParam
    );

    @WebMethod
    @RequestWrapper(localName = "requestSubscription", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.RequestSubscription")
    @ResponseWrapper(localName = "requestSubscriptionResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.RequestSubscriptionResponse")
    @WebResult(name = "requestSubscriptionResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.RequestSubscriptionResult requestSubscription(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "requestSubscriptionParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.RequestSubscriptionParam requestSubscriptionParam
    );

    @WebMethod
    @RequestWrapper(localName = "pingService", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.PingService")
    @ResponseWrapper(localName = "pingServiceResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.PingServiceResponse")
    @WebResult(name = "pingServiceResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.PingServiceResult pingService();

    @WebMethod
    @RequestWrapper(localName = "updateContactUser", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.UpdateContactUser")
    @ResponseWrapper(localName = "updateContactUserResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.UpdateContactUserResponse")
    @WebResult(name = "updateContactUserResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.UpdateContactUserResult updateContactUser(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "updateContactUserParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.UpdateContactUserParam updateContactUserParam
    );

    @WebMethod
    @RequestWrapper(localName = "launchProcedure", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.LaunchProcedure")
    @ResponseWrapper(localName = "launchProcedureResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.LaunchProcedureResponse")
    @WebResult(name = "launchProcedureResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.LaunchProcedureResult launchProcedure(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "launchProcedureParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.LaunchProcedureParam launchProcedureParam
    );

    @WebMethod
    @RequestWrapper(localName = "createContactUser", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.CreateContactUser")
    @ResponseWrapper(localName = "createContactUserResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.CreateContactUserResponse")
    @WebResult(name = "createContactUserResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.CreateContactUserResult createContactUser(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "createContactUserParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.CreateContactUserParam createContactUserParam
    );

    @WebMethod
    @RequestWrapper(localName = "deleteContactUser", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.DeleteContactUser")
    @ResponseWrapper(localName = "deleteContactUserResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.DeleteContactUserResponse")
    @WebResult(name = "deleteContactUserResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.DeleteContactUserResult deleteContactUser(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "deleteContactUserParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.DeleteContactUserParam deleteContactUserParam
    );

    @WebMethod
    @RequestWrapper(localName = "listCmcDefinition", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListCmcDefinition")
    @ResponseWrapper(localName = "listCmcDefinitionResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListCmcDefinitionResponse")
    @WebResult(name = "listCmcDefinitionResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.ListCmcDefinitionResult listCmcDefinition(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "listCmcDefinitionParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.ListCmcDefinitionParam listCmcDefinitionParam
    );

    @WebMethod
    @RequestWrapper(localName = "listManagementUnit", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListManagementUnit")
    @ResponseWrapper(localName = "listManagementUnitResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.ListManagementUnitResponse")
    @WebResult(name = "listManagementUnitResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.ListManagementUnitResult listManagementUnit(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "listManagementUnitParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.ListManagementUnitParam listManagementUnitParam
    );

    @WebMethod
    @RequestWrapper(localName = "launchCmc", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.LaunchCmc")
    @ResponseWrapper(localName = "launchCmcResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "net.alarmtilt.cle.alarmis.client.LaunchCmcResponse")
    @WebResult(name = "launchCmcResult", targetNamespace = "")
    public net.alarmtilt.cle.alarmis.client.LaunchCmcResult launchCmc(
        @WebParam(name = "authParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.AuthParam authParam,
        @WebParam(name = "launchCmcParam", targetNamespace = "")
        net.alarmtilt.cle.alarmis.client.LaunchCmcParam launchCmcParam
    );
}
